ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "http://0.0.0.0:8080/"
  audience: "client"
  issuer: "http://0.0.0.0:8080/"
  realm: "ktor-blog-api"
  claimField: "id"

database:
  url: "jdbc:mysql://trolley.proxy.rlwy.net:20249/railway?useSSL=true&serverTimezone=UTC"
  user: "root"
  driver: "com.mysql.cj.jdbc.Driver"
  host: "mysql.railway.internal"
  port: "3306"
  name: "railway"
  password: "PdrEhCLoDppXgOjDlKCJywZJqjfubaqC"
