ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://kmpktorbackend-production.up.railway.app/"
  audience: "client"
  realm: "daring-radiance"
  claimField: "id"
  jwt_secret: "z7e5KfV9pJ2q$WcM3!mT"

database:
  url: "jdbc:mysql://trolley.proxy.rlwy.net:20249/railway?useSSL=true&serverTimezone=UTC"
  user: "root"
  driver: "com.mysql.cj.jdbc.Driver"
  host: "mysql.railway.internal"
  port: "3306"
  name: "railway"
  password: "PdrEhCLoDppXgOjDlKCJywZJqjfubaqC"
